[nano_lora_plus]
extends = esp32_base
board = nano_lora_plus
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.partitions = default_16MB.csv
monitor_filters = esp32_exception_decoder
build_flags =
  ${esp32_base.build_flags}
  -I variants/nano_lora_plus
  -D NANO_LORA_PLUS
  -D LORA_FREQ=495.2
  -D LORA_BW=125
  -D LORA_SF=9
  -D LORA_CR=5
  -D RADIO_CLASS=CustomLR2021
  -D WRAPPER_CLASS=CustomLR2021Wrapper
  -D PIN_BOARD_SDA=18
  -D PIN_BOARD_SCL=17
  -D LED_PIN=48
  -D LED_STATE_ON=1
  -D PIN_USER_BTN=0
  -D P_LORA_SCLK=5
  -D P_LORA_MISO=3
  -D P_LORA_MOSI=6
  -D P_LORA_NSS=7
  -D P_LORA_DIO_1=11
  -D P_LORA_BUSY=15
  -D P_LORA_RESET=8
  -D LR2021_IRQ_DIO=11
  -D LR2021_TCXO_VOLTAGE=0.0
  -D LORA_TX_POWER=22
  -D PIN_VBAT_READ=1
  -D ADC_MULTIPLIER=2.0f
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/nano_lora_plus>
lib_deps =
  SPI
  Wire
  jgromes/RadioLib @ ^7.7.1
  rweather/Crypto @ ^0.4.0
  adafruit/RTClib @ ^2.1.3
  melopero/Melopero RV3028 @ ^1.1.0
  electroniccats/CayenneLPP @ 1.6.1

[env:nano_lora_plus_companion_radio_usb]
extends = nano_lora_plus
build_flags =
  ${nano_lora_plus.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D DISPLAY_CLASS=SSD1306Display
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter = ${nano_lora_plus.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${nano_lora_plus.lib_deps}
  densaugeo/base64 @ ~1.4.0
  adafruit/Adafruit SSD1306 @ ^2.5.16

[env:nano_lora_plus_companion_radio_ble]
extends = nano_lora_plus
build_flags =
  ${nano_lora_plus.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D DISPLAY_CLASS=SSD1306Display
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter = ${nano_lora_plus.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${nano_lora_plus.lib_deps}
  densaugeo/base64 @ ~1.4.0
  adafruit/Adafruit SSD1306 @ ^2.5.16
